service:
  name: serverless-demo

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  myStage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  serverless-offline:
    host: 0.0.0.0
    port: 3000
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.myStage}
  region: ${self:custom.region}
  environment:
    STAGE: ${self:custom.myStage}
    REGION: ${self:custom.region}

functions:
  helloWorld:
    handler: src/endpoints/index.handler
    events:
      - http:
          path: /
          method: get

package:
  include:
    - src/**
  exclude:
    - .git/**
    - __tests__/**

plugins:
  - serverless-dynamodb-local
  - serverless-offline